# Serviço Florestal Brasileiro (SFB)

O SFB é um órgão vinculado ao Ministério do Meio Ambiente e Mudança do Clima (MMA), criado em 2006 com o objetivo principal de promover o uso econômico e sustentável das florestas públicas brasileiras. Suas atribuições são amplas e visam garantir a conservação dos recursos florestais enquanto fomentam o desenvolvimento sustentável.

<br>

### Sistema Nacional de Cadastro Ambiental Rural

O **SICAR** é uma plataforma eletrônica que gerencia o Cadastro Ambiental Rural (CAR). O CAR, por sua vez, é um registro público eletrônico de âmbito nacional, obrigatório para todos os imóveis rurais, sejam eles propriedades ou posses. Sua finalidade é integrar as informações ambientais dos imóveis rurais, como áreas de floresta nativa, áreas de preservação permanente (APP), reserva legal (RL) e áreas de uso consolidado.

Os principais objetivos do SICAR são:

- Controle e Monitoramento: O SICAR permite o controle e monitoramento das áreas ambientais dos imóveis rurais, auxiliando na identificação de desmatamentos ilegais e no planejamento ambiental.
- Planejamento Ambiental e Econômico: As informações do CAR, acessíveis via SICAR, subsidiam o planejamento ambiental e econômico do uso do solo, contribuindo para uma agricultura mais sustentável.
- Regularização Ambiental: A inscrição no CAR é o primeiro passo para a regularização ambiental do imóvel rural. Por meio do SICAR, os proprietários podem aderir ao Programa de Regularização Ambiental (PRA) e, assim, regularizar passivos ambientais.
- Base de Dados Pública: O SICAR disponibiliza informações de natureza pública sobre a regularização ambiental dos imóveis rurais, promovendo a transparência e subsidiando a fiscalização.

[![SICAR](./../../../assets/br/sfb/sicar.jpg)](https://consultapublica.car.gov.br/publico/imoveis/index){target="\_blank"}

<br>

Com auxílio do pacote [SICAR](https://github.com/urbanogilson/SICAR), desenvolvido pelo [Gilson Urbano](https://github.com/urbanogilson) foi possível adicionar a funcionalidade de obtenção de dados do **Sistema Nacional de Cadastro Ambiental Rural (SICAR)**.

O pacote obtem os dados da [Base de Dowloads](https://consultapublica.car.gov.br/publico/estados/downloads) e utiliza o [tesseract](https://github.com/tesseract-ocr/tesseract/) para passar pelo _recapcha_.

<br>

---

<br>

<div class="admonition info">
    <p class="admonition-title">Informação</p>
    <br>
    <p>
        Em 13.06.2025 observei que há a possibilidade de acessar o <a href="https://geoserver.car.gov.br/geoserver/" target=_blank>GeoServer</a> do SICAR, facilitando muito a obtenção de dados.
    </p>

</div>

In [1]:
import tempfile
from pathlib import Path

import geopandas as gpd

import open_geodata as geo

<br>

O pacote tem como dependência o *Tesseract* e é necessário instalar e apontar o caminho do executável na aplicação.

<div class="admonition info">
    <p class="admonition-title">Informação</p>
    <br>
    <p>
        O <a href="https://github.com/tesseract-ocr/tesseract/" target=_blank>Tesseract</a> (Google Tesseract OCR) é uma ferramenta de reconhecimento óptico de caracteres (OCR) que permite extrair texto de imagens. Ele é muito usado para digitalizar documentos, ler textos de fotos ou PDFs escaneados, e automatizar tarefas que envolvem leitura de texto visual.
    </p>
</div>

<br>

Uma vez com o [Tesseract](https://tesseract-ocr.github.io/tessdoc/Installation.html) instalado, é necessário indicar qual o caminho para o executável.

In [2]:
# Instancia classe IBGE
sfb = geo.br.sicar.SICAR(
    tesseract_path='C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
)

<br>

---

## Propriedades

In [3]:
sfb.release_dates

{<State.AC: 'AC'>: '08/07/2025',
 <State.AL: 'AL'>: '08/07/2025',
 <State.AP: 'AP'>: '01/07/2025',
 <State.AM: 'AM'>: '08/07/2025',
 <State.BA: 'BA'>: '01/07/2025',
 <State.CE: 'CE'>: '10/07/2025',
 <State.DF: 'DF'>: '01/07/2025',
 <State.ES: 'ES'>: '10/07/2025',
 <State.GO: 'GO'>: '08/07/2025',
 <State.MA: 'MA'>: '03/07/2025',
 <State.MT: 'MT'>: '08/07/2025',
 <State.MS: 'MS'>: '01/07/2025',
 <State.MG: 'MG'>: '01/07/2025',
 <State.PA: 'PA'>: '08/07/2025',
 <State.PB: 'PB'>: '10/07/2025',
 <State.PR: 'PR'>: '01/07/2025',
 <State.PE: 'PE'>: '03/07/2025',
 <State.PI: 'PI'>: '03/07/2025',
 <State.RJ: 'RJ'>: '03/07/2025',
 <State.RN: 'RN'>: '03/07/2025',
 <State.RS: 'RS'>: '10/07/2025',
 <State.RO: 'RO'>: '03/07/2025',
 <State.RR: 'RR'>: '10/07/2025',
 <State.SC: 'SC'>: '03/07/2025',
 <State.SP: 'SP'>: '01/07/2025',
 <State.SE: 'SE'>: '10/07/2025',
 <State.TO: 'TO'>: '09/07/2025'}

In [4]:
sfb.list_layers

[<Polygon.AREA_PROPERTY: 'AREA_IMOVEL'>,
 <Polygon.APPS: 'APPS'>,
 <Polygon.NATIVE_VEGETATION: 'VEGETACAO_NATIVA'>,
 <Polygon.CONSOLIDATED_AREA: 'AREA_CONSOLIDADA'>,
 <Polygon.AREA_FALL: 'AREA_POUSIO'>,
 <Polygon.HYDROGRAPHY: 'HIDROGRAFIA'>,
 <Polygon.RESTRICTED_USE: 'USO_RESTRITO'>,
 <Polygon.ADMINISTRATIVE_SERVICE: 'SERVIDAO_ADMINISTRATIVA'>,
 <Polygon.LEGAL_RESERVE: 'RESERVA_LEGAL'>]

In [5]:
sfb.list_states

[<State.AC: 'AC'>,
 <State.AL: 'AL'>,
 <State.AM: 'AM'>,
 <State.AP: 'AP'>,
 <State.BA: 'BA'>,
 <State.CE: 'CE'>,
 <State.DF: 'DF'>,
 <State.ES: 'ES'>,
 <State.GO: 'GO'>,
 <State.MA: 'MA'>,
 <State.MG: 'MG'>,
 <State.MS: 'MS'>,
 <State.MT: 'MT'>,
 <State.PA: 'PA'>,
 <State.PB: 'PB'>,
 <State.PE: 'PE'>,
 <State.PI: 'PI'>,
 <State.PR: 'PR'>,
 <State.RJ: 'RJ'>,
 <State.RN: 'RN'>,
 <State.RO: 'RO'>,
 <State.RR: 'RR'>,
 <State.RS: 'RS'>,
 <State.SC: 'SC'>,
 <State.SE: 'SE'>,
 <State.SP: 'SP'>,
 <State.TO: 'TO'>]

<br>

---

## _Download_

In [ ]:
# Donwload Data
with tempfile.TemporaryDirectory() as temp_dir:
    # Cria o caminho temporário em formato Path
    temp_path = Path(temp_dir)

    # Download
    sfb.download_data(
        sigla_estado=geo.br.sicar.State.AC,
        layer=geo.br.sicar.Polygon.AREA_PROPERTY,
        output_path=temp_path,
    )

    # Lista arquivos baixados
    list_files = list(temp_path.glob('*'))
    print(list_files)

    # Lê o shapefile diretamente do zip
    gdf = gpd.read_file(filename=list_files[0])

Downloading polygon 'AREA_IMOVEL' for state 'AC': 100%|██████████| 14.5M/14.5M [00:00<00:00, 34.4MiB/s]

Polygon for State.AC downloaded successfully.
[WindowsPath('C:/Users/michel/AppData/Local/Temp/tmp8varrouv/AC_AREA_IMOVEL.zip')]

<brt>

<br>

-----

## Filtrar

Olhamos a estrutura dos dados baixados.

In [7]:
gdf.info()
gdf.head(2)

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 57199 entries, 0 to 57198
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cod_tema    57199 non-null  object
 1   nom_tema    57199 non-null  object
 2   cod_imovel  57199 non-null  object
 3   mod_fiscal  57199 non-null  float64
 4   num_area    57199 non-null  float64
 5   ind_status  57199 non-null  object
 6   ind_tipo    57199 non-null  object
 7   des_condic  57199 non-null  object
 8   municipio   57199 non-null  object
 9   cod_estado  57199 non-null  object
 10  dat_criaca  57199 non-null  object
 11  dat_atuali  57197 non-null  object
 12  geometry    57199 non-null  geometry
dtypes: float64(2), geometry(1), object(10)
memory usage: 5.7+ MB

,cod_tema,nom_tema,cod_imovel,mod_fiscal,num_area,ind_status,ind_tipo,des_condic,municipio,cod_estado,dat_criaca,dat_atuali,geometry
0,AREA_IMOVEL,Area do Imovel,AC-1200013-4DA9D6F741224F9DBE2CCD6E3472CDA3,0.3396,33.9636,AT,IRU,Aguardando analise,Acrelandia,AC,03/06/2014,07/07/2025,"POLYGON ((-67.11295 -9.76117, -67.11261 -9.761..."
1,AREA_IMOVEL,Area do Imovel,AC-1200013-67DC8631B8DF4390AC3B0449B5FE2659,0.3629,36.2879,PE,IRU,Aguardando analise,Acrelandia,AC,10/05/2023,10/05/2023,"POLYGON ((-67.07133 -9.73266, -67.0657 -9.7481..."

<br>

E filtramos de formas diferentes.

In [8]:
# Filtra propriedades com área definida em um intervalo de áreas (em hectares)
gdf = gdf[(gdf['num_area'] >= 20) & (gdf['num_area'] <= 21)]

# Exibe informações do GeoDataFrame filtrado
gdf.info()
gdf.head(2)

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 716 entries, 46 to 57155
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cod_tema    716 non-null    object
 1   nom_tema    716 non-null    object
 2   cod_imovel  716 non-null    object
 3   mod_fiscal  716 non-null    float64
 4   num_area    716 non-null    float64
 5   ind_status  716 non-null    object
 6   ind_tipo    716 non-null    object
 7   des_condic  716 non-null    object
 8   municipio   716 non-null    object
 9   cod_estado  716 non-null    object
 10  dat_criaca  716 non-null    object
 11  dat_atuali  716 non-null    object
 12  geometry    716 non-null    geometry
dtypes: float64(2), geometry(1), object(10)
memory usage: 78.3+ KB

,cod_tema,nom_tema,cod_imovel,mod_fiscal,num_area,ind_status,ind_tipo,des_condic,municipio,cod_estado,dat_criaca,dat_atuali,geometry
46,AREA_IMOVEL,Area do Imovel,AC-1200013-C4B47B59683E40D490D7860F6E1B6A1A,0.2008,20.0779,AT,IRU,Aguardando analise,Acrelandia,AC,11/11/2019,27/06/2025,"POLYGON ((-66.79678 -9.92364, -66.79617 -9.924..."
260,AREA_IMOVEL,Area do Imovel,AC-1200013-6EA647753BF645DBAA518949C82F1958,0.2058,20.5794,AT,IRU,Aguardando analise,Acrelandia,AC,12/03/2025,12/03/2025,"POLYGON ((-66.99726 -9.96755, -66.99536 -9.967..."

In [9]:
# # Filtra Propriedades com 4 ou mais módulos fiscais
# gdf = gdf[gdf['mod_fiscal'] >= 4]

# # Results
# gdf.info()
# gdf.head(2)

In [10]:
# # Obtem as 100 maiores propriedades do Estado
# gdf = gdf.sort_values(by=['num_area'], ascending=False)
# gdf = gdf[0:30]

# # Results
# gdf.info()
# gdf.head(2)

<br>

E plotamos o resultado.

In [11]:
gdf.explore(column='des_condic', tiles='Esri.WorldImagery')